version: '3'

services:

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - laravel

  django:
    build: .
    restart: always
    container_name: django
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py seed_superuser &&
        gunicorn private_equity.wsgi -b 0.0.0.0:80
      "
    depends_on:
      - postgres
    volumes:
      - django-shop-users:/app/

  laravel:
    build: .
    restart: always
    container_name: laravel
    depends_on:
      - postgres
    volumes:
      - ./eCommerce_back:/app/

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file: ../../src/.env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 9000:5432

volumes:
  db:
