version: '3'

services:

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - laravel

  django:
    build: ./django-shop-users/.
    restart: always
    container_name: django
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py seed_superuser &&
        python runserver 0.0.0.0:80
      "
    depends_on:
      - database
    volumes:
      - ./django-shop-users:/app/

  laravel:
    build: ./eCommerce_back/.
    restart: always
    container_name: laravel
    depends_on:
      - database
    volumes:
      - ./eCommerce_back:/app/

  database:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3306
    # volumes:
    #   - db:/var/lib/mysql
    ports:
      - 9000:3306

volumes:
  db:
